### ISSUE TITLE
Europython 2018 Sprints Thanks

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#108]
Just opening this issue to offer my personal thanks to contributors at the Europython 2018 sprints!

Here's who did what:

* @MarkAColes diligently triaged and closed several issues in the issue tracker as well as applying documentation fixes.
* @gustavooferreira refactored work by @Avaren on a storage API (#99) (super close to being merged)
* @a96tudor has nearly implemented scale and flip for actors (#36) (just a positioning bug left to fix)
* @mariaS210 and @the-artists-formerly-known-as-spam worked on gamepad support (thanks also to @nanoflite who has looked into this)
* @Ava-O and @conniepocky helped prevent users getting confused by installing Pygame Zero on Python 2
* @jvikman fixed a bug in the asteroids example
* @alisdt added `screen.bounds()` which simplifies testing if an Actor is on-screen
* @virtuallight fixed failing tests due to alpha-blending rounding variations
* @tropxy worked on timing in-game events
* @tonysimpson looked into crashes in libsdl_mixer (#55)
* @BibianaC started a Catalan translation of the docs
* @SunOfCam fixed some typos in the Chinese translation of the docs by @yonghuming
* @nlaurance promised a French translation of the docs
* I added [a REPL](https://pygame-zero.readthedocs.io/en/latest/repl.html)

Now that we have all gone home and have other things to do it's easy to forget all about this and let your contributions go to waste. Please can you make sure any work you did is pushed to Github and linked to appropriate issues.

I'd also like to get people credited in our [AUTHORS file](https://github.com/lordmauve/pgzero/blob/master/AUTHORS) for their contributions although at present it seems that hasn't been updated since 2015 when Richard and I started the project. Please can you let me know who to credit (especially if your real name isn't in your Github profile)?

**Comment by virtuallight** [comment]
@lordmauve Hi! Thanks for recognition. I'm fine with skipping this round of AUTHORS update and maybe being added there once I contribute a bit more than a single, small patch. 

Thank you also for organizing the sprint! I always had a hard time choosing what to sprint on as most of the topics weren't much fun for me 😁 Gaming FTW 👾

**Comment by yonghuming** [comment]
and i have done some chinese translation
