### ISSUE TITLE
Actor transparency

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#117]
At the Pycon UK Dojo in September 2018 many teams worked on ["Four Seasons" demos](https://github.com/PyconUK/dojo18).

One of the things that was commonly asked about was alpha-blending support.

We should investigate to what extent this is possible in Pygame and if feasible, implement this in Pygame Zero.

**Comment by charlesej** [comment]
Is this the same as functionality that currently exists by setting the Actor's `.opacity` (#125), or are you looking for something different here?

**Comment by lordmauve** [comment]
Yes, it's the same feature. I've now added [documentation for this feature](https://pygame-zero.readthedocs.io/en/latest/builtins.html#transparency) so closing this issue.
