### ISSUE TITLE
Closing repl with exit() messes up terminal

### ISSUE THREAD

**Issue by DavidS48** [lordmauve/pgzero#121]
Ran an example game with the repl. Closed the game window and then used exit() to close the repl - terminal echo mode seems to be off.

Closing the repl with Ctrl-D behaves as expected.

**Comment by DavidS48** [comment]
I'm going to have a look at this...

**Comment by DavidS48** [comment]
I suspect that this is a ptpython issue - I've raised issue #257 there.

**Comment by lordmauve** [comment]
Removed the REPL feature because it was half-baked.
