### ISSUE TITLE
module 'pgzrun' has no attribute 'go'

### ISSUE THREAD

**Issue by JoBilert** [lordmauve/pgzero#133]
I followed the manual for using pygame zero with IDLE and tried the example code given in https://pygame-zero.readthedocs.io/en/latest/ide-mode.html . But I always get the following error on the python console:

>traceback (most recent call last):
  File "E:\WPy-3702\notebooks\pgzero.py", line 1, in <module>
    import pgzrun
  File "E:\WPy-3702\python-3.7.0.amd64\lib\site-packages\pgzrun.py", line 13, in <module>
    from pgzero.runner import prepare_mod, run_mod
  File "E:\WPy-3702\notebooks\pgzero.py", line 10, in <module>
    pgzrun.go()
AttributeError: module 'pgzrun' has no attribute 'go'
>

Can anybody help me with that?

**Comment by TechnoVisual** [comment]
Hi - it's possible that you are using an old version of pgzrun - I think go is only available from V1.2. Try re-installing from a fresh download.

**Comment by JoBilert** [comment]
OK.

Am 5. Oktober 2018 1:41:29 nachm. schrieb Mark Vanstone 
<notifications@github.com>:

**Comment by lordmauve** [comment]
Actually I don't think that is the problem - you wouldn't have a `pgzrun` module at all if your Pygame Zero installation was too old for `pgzrun.go()`.

But I notice your game script is called `pgzero.py` - I imagine that is what is breaking it. You should choose any other name.

**Comment by JoBilert** [comment]
Foundation the problem. There were remainders of an old Python installation 
oh my drive. After I removed it everything worked smoothly. Thanks for the 
help though.

Am 5. Oktober 2018 5:50:48 nachm. schrieb Daniel Pope 
<notifications@github.com>:
