### ISSUE TITLE
keyboard.return doesn't work as return is a Python reserved word

### ISSUE THREAD

**Issue by penguintutor** [lordmauve/pgzero#134]
I am unable to use keyboard.return to check for the status of the return key on the keyboard.

This is because lowercase return is a reserved word in Python (to return from a function / method). 

It works OK if I use RETURN or K_RETURN, except that it then issues the depreciated usage error message. 

A possible solution would be to add an additional different word perhaps rtn which is translated to RETURN. I'd be happy to add this myself and issue a PR, but it doesn't feel like a particularly elegant solution. 

Is there another way to use the return key in the keyboard class?
Or would you like me to add rtn as a workaround?

**Comment by lordmauve** [comment]
Oh! I never thought of that.

You could add `enter` as an alias? I wonder if there are any others that would be reserved... I can't think of any.

**Comment by penguintutor** [comment]
I think it's just return that is a problem. Other potential words such as shift are referred to as lshift / rshift etc. 

I didn't think it would be possible to use enter as keyboards also have an enter key on the keypad, but looking at Pygame that uses: KP_ENTER (for keypad enter), so there is no conflict. 

I've submitted a pull-request which just checks for enter and replaces that with return.

**Comment by lordmauve** [comment]
Fixed in 8aefd123ebbaf9fd8f3de6953c72b77ee1794a0c.
