### ISSUE TITLE
Docs: slovak translation

### ISSUE THREAD

**Issue by bletvaska** [lordmauve/pgzero#138]
WIP at https://github.com/bletvaska/pgzero-slovak

current state of the art: https://pgzero-slovak.readthedocs.io/sk/latest/

**Comment by lordmauve** [comment]
Hi (sorry for the delay in getting back to this). This looks like a great start. I see a fair bit of English still but I'm sure this is valuable to learners. I will link this up so it will appear as the official Slovak translation.

**Comment by lordmauve** [comment]
I seem to no longer have the option to do this. Can you add me as a maintainer on the ReadTheDocs project, ie. at https://readthedocs.org/projects/pgzero-slovak/?

**Comment by bletvaska** [comment]
no problem. but what is your username in Read The Docs project?

mirek

po 6. 5. 2019 o 22:34 Daniel Pope <notifications@github.com> napísal(a):

**Comment by lordmauve** [comment]
Ah, thought it was the same, but it isn't. I'm `mauve` on ReadTheDocs.

**Comment by bletvaska** [comment]
ok. you are the maintainer of the slovak translation.

mirek

ut 7. 5. 2019 o 15:49 Daniel Pope <notifications@github.com> napísal(a):

**Comment by lordmauve** [comment]
Ok, all sorted. You should now show up as the Slovak translation of pygame-zero.readthedocs.io
