### ISSUE TITLE
Re-scale an actor in pgzero?

### ISSUE THREAD

**Issue by PerspexSphinx** [lordmauve/pgzero#143]
Hi,
Maybe I’m missing something obvious but…
…is there a way to re-scale an actor (sprite) in pgzero?

I have asked in the Raspberry Pi forums (Board index > Projects > Gaming) and it was suggested I ask the developer/maintainer, which I guess is you guys?

“I would not have thought that one would have to resort to “coding alchemy” just to re-scaling a sprite when you’ve made it’s super simple to rotate an Actor (sprite)!”

I’m just a bit mystified....

**Comment by lordmauve** [comment]
This is in progress under #36. In the meantime you can use [pygame.transform.scale()](https://www.pygame.org/docs/ref/transform.html#pygame.transform.scale) to scale a Surface before passing it to Actor.
