### ISSUE TITLE
Pygame Zero non-functional on Mac OS X Mojave

### ISSUE THREAD

**Issue by chriswoollard** [lordmauve/pgzero#145]
I have been trying to get Pygame Zero to work on a Mac. Everything seems to be okay, but when a window is displayed it is just empty.

I have tried lots of different examples, including the flappy bird's example, but nothing works. It just brings up a blank grey window with no contents.

I am Running Apple OS X Mojave with Python 3.7.1 from Homebrew.

Is there any reason that this is not working?

Chris

**Comment by chriswoollard** [comment]
I have noticed that the following appears in my system.log when running examples. It may be important.

Dec 18 09:50:31 Python[4468]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Dec 18 09:51:09 Python[4475]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug

**Comment by lordmauve** [comment]
What version of Pygame are you using?

**Comment by chriswoollard** [comment]
pygame 1.9.4
pgzero 1.2

**Comment by lordmauve** [comment]
Could you try with Pygame 1.9.3? Also, are you using a virtualenv/venv etc?

**Comment by chriswoollard** [comment]
I have tried, but previous versions 1.9.3 and 1.9.2 won't install. THey generate errors. I will see if i can work out why.

**Comment by da4089** [comment]
I have a similar problem:

macOS Mojave 10.14
Python 3.6.7 (from MacPorts)
pgzero 1.2
pygame 1.9.4

I am using a virtualenv (from MacPorts)

I *don't* get the libdispatch error in system.log, fwiw.

I do get just a blank window (I tried just a `screen.fill` in my `draw` method).  Putting a `print` in the `draw` method shows that it *is* being called, but there's nothing shows in the window.

**Comment by da4089** [comment]
> I do get just a blank window (I tried just a `screen.fill` in my `draw` method). Putting a `print` in the `draw` method shows that it _is_ being called, but there's nothing shows in the window.

I have now also attempted a very basic PyGame application, with the same result.  So ... I am assuming this is an issue with PyGame, not PyGame Zero.

**Comment by da4089** [comment]
> I have now also attempted a very basic PyGame application, with the same result. So ... I am assuming this is an issue with PyGame, not PyGame Zero.

See this PyGame issue for discussion of possible fixes.  There doesn't seem to be a clear pattern, with some folks finding 3.6.x broken, others reporting it fixing their problem.

https://github.com/pygame/pygame/issues/555

**Comment by lordmauve** [comment]
Pygame 2.0dev* seems to fix this issue.

It can be installed with `pip install --upgrade --pre 'pygame>2'`

**Comment by adespoton** [comment]
> Pygame 2.0dev* seems to fix this issue.
> 
> It can be installed with `pip install --upgrade --pre 'pygame>2'`

I've got Pygame 2.0dev10 installed, but when using pgzrun, it still reports using 1.9.6?  Is pgz pulling its pygame libs from somewhere other than the default python3 library tree, or is something else going on?

[edit] probably worth noting: Catalina, Python 3.7, PyGame Zero 1.2, PyGame 2.0.0.dev10, but reporting as pygame 1.9.6 inside pgzrun and via pip3 show pygame.  And image.load is successful, but nothing is actually drawn to the window, as with 1.9.6 and Mojave.

**Comment by DrNebin** [comment]
I have this same issue. Is there a resolution? I am on Big Sur.

**Comment by lordmauve** [comment]
Pygame Zero now uses PyGame 2.x so I think this issue will no longer occur.
