### ISSUE TITLE
Actor's opacity returns incorrect value

### ISSUE THREAD

**Issue by charlesej** [lordmauve/pgzero#162]
Calling the Actor's `.opacity` getter gives unexpected values.

Expected result: Should return the value the user set (if it was in the acceptable range of [0.0, 1.0]).
Actual result: Currently only returning int values of 0 or 1. 

This code will reproduce the issue.

```
# Test if users get back the same opacity values as they set.
alien = Actor('alien')

for opacity in (0.0, 0.2, 0.5, 0.99, 1.0):
    alien.opacity = opacity

    if alien.opacity == opacity:
        print('PASS: (alien.opacity) {} == {} (expected_opacity)'.format(
            alien.opacity, opacity))
    else:
        print('FAIL: (alien.opacity) {} != {} (expected_opacity)'.format(
            alien.opacity, opacity))
```

Running the above code give this output.

```
PASS: (alien.opacity) 0 == 0.0 (expected_opacity)
FAIL: (alien.opacity) 0 != 0.2 (expected_opacity)
FAIL: (alien.opacity) 0 != 0.5 (expected_opacity)
FAIL: (alien.opacity) 0 != 0.99 (expected_opacity)
PASS: (alien.opacity) 1 == 1.0 (expected_opacity)
```

System details:
- os: windows 10
- python: 3.5.0
- pygame: 1.9.4
- pgzero: master branch at ef963beaa22db89cb011695e96587bb268cbec2a
- numpy: 1.15.4

**Comment by lordmauve** [comment]
Fixed - thanks @charlesej !
