### ISSUE TITLE
Error (TypeError) when Actor's opacity set outside of valid range

### ISSUE THREAD

**Issue by charlesej** [lordmauve/pgzero#163]
Setting opacity outside the acceptable range of [0.0, 1.0] is not prevented and will cause an error when the actor is drawn 

Expected result: Values outside of the acceptable range should be clipped to the range.
Actual result: Values outside the acceptable range are accepted and an error occurs when they are used.

This code will reproduce the issue.

```
alien = Actor('alien', topleft=(0,0))
alien.opacity = 1.1
# alien.opacity = -0.1  # Values < 0.0 result in the same error.

def draw():
    alien.draw()
```

Running the above code will cause an error like the following (Note: file path edited).

```
  File "\pgzero\pgzero\actor.py", line 81, in _set_opacity
    alpha_img.fill((255, 255, 255, actor._opacity))
TypeError: invalid color argument
```

System details:
- os: windows 10
- python: 3.5.0
- pygame: 1.9.4
- pgzero: master branch at ef963beaa22db89cb011695e96587bb268cbec2a
- numpy: 1.15.4

**Comment by lordmauve** [comment]
Fixed in cbdb1f114effd925628a1f466662d981f09e9534
