### ISSUE TITLE
macOS | Mu related | Exception running code with non-ASCII comments

### ISSUE THREAD

**Issue by tmontes** [lordmauve/pgzero#173]
@lordmauve,

Thanks a lot for sharing pgzero, it feels like an incredible library which I'be been exploring in the process of planning a kid-oriented workshop: building on tools like [Mu](https://github.com/mu-editor/mu) and pgzero is incredible!

Having said that, I'm facing a particular failure with the combination of both; that is, when running Mu in Pygame Zero mode. I've logged an issue in the Mu issue tracker [here](https://github.com/mu-editor/mu/issues/746) but from my analysis, it boils down to a possible fix in Pygame Zero.

I have all the details the the [Mu issue](https://github.com/mu-editor/mu/issues/746) which I invite you to check but, simplifying it a lot:

* Mu running on macOS launched from the Finder / LaunchPad: in other words, launched like any non-technical person would launch it (others, like me might launch it from a terminal which would not lead to the failure).
* When running a project in Pygame Zero mode, the code that reads the `*py` module to be run, in `runner.py` raises an exception:

```python
    with open(path) as f:
        src = f.read()                                                                    
```

* Why, long story short:
  * macOS processes launched from the Finder / LaunchPad don't get env vars like LANG, LC_CTYPE, etc.
  * CPython thus defaults to using `US-ASCII` by default in the `open` call that is used.
  * Decoding non-ASCII text then fails.

Possible fix:
* Given that `compile` can take a byte string -- [see docs](
https://docs.python.org/3/library/functions.html#compile) -- maybe just adding a `mode='rb'` to the `open` call is enough.
* It tested it out on my system and it worked fine.
* I did not look at the full codebase for pgzero and, thus, this may not make sense.

I would be happy to hear your evaluation and, within reason, to contribute to such a fix, once one is deemed acceptable.

Again thanks.

**Comment by tmontes** [comment]
@lordmauve,

I came back here to check on any progress / feedback. While re-reading the issue I realised **I omitted one fundamental fact** from my description -- sorry for that!

The exception I mentioned `pgzero` raises while reading the module from the filesystem is raised iff:
* Mu is running on macOS launched from the Finder / LaunchPad (that is, GUI launched).
* The code includes non-ASCII characters (common in non-English native kids code comments).

An updated Mu release is in the works and I would love it not to fail in such scenario. Please let me know if you agree with my proposed solution and would be willing to integrate such a fix.

Thanks again. :)

**Comment by lordmauve** [comment]
Oh, yeah, this is absolutely a bug in Pygame Zero. I will commit a fix.

**Comment by lordmauve** [comment]
Fixed in 97c989dda2c7d82260551a6cc5762ed0248d91a3. I changed it to compile from bytes, which means that "coding" headers will be respected and that it falls back to utf-8 (I think, turns out it's hard to design a test).

Since 3.7, Python has `PYTHONCOERCECLOCALE` which means that UTF-8 is used if no LC_ALL/LANG/LC_CTYPE environment vars are set.

So that just leaves Mu to solve the more difficult problem of ensuring that it writes files in the correct encoding and also tells the interpreter to run with that encoding.

**Comment by tmontes** [comment]
@lordmauve, thanks for following up. I took a look at the commit and the changes related to this look fine, AFAICT. But I wasn't expecting it to have other changes so it scared me a bit at first! :)

PS: Which plans do you have, if any, regarding releasing an updated version that Mu could depend on?

**Comment by tmontes** [comment]
Hey @lordmauve, Mu is moving towards an updated release... It would be wonderful to include the fix for this issue. For that, an updated `pgzero` release would be really helpful. :)

May I help you in that process somehow? Thanks in advance.

**Comment by lordmauve** [comment]
Ok, let me try to cut a release in the next few days. I might have to cherry-pick a 1.2.1.

**Comment by tmontes** [comment]
Thanks for that... But please don't feel rushed! Being unaware of @ntoll's plans for the next non-alpha/beta/rc Mu release, I'd say that we're a few weeks away, at least. If sooner is better for you, then great. :)

Let me know if there's anything I might be able to help out with -- testing it out with Windows and macOS packaged Mu versions is guaranteed. :)
