### ISSUE TITLE
How to import other scripts that use pgzero?

### ISSUE THREAD

**Issue by bokov** [lordmauve/pgzero#176]
Let's say I have a script with the main game logic, and a separate script to hold long repetitive data objects.

game_data.py

    import pgzrun
    imglist = [images.floor, images.pillar, images.soil]

mygame.py:

    import pgzrun
    WIDTH = 800
    HEIGHT =600
    from game_data import *
     
    def draw():
        screen.blit(imglist[0],(10,10))
        screen.blit(imglist[1],(40,40))
        screen.blit(imglist[2],(70,70))
    pgzrun.go()

If I run `game_data.py` directly it runs fine. But if I run `mygame.py`, it give the error: 

    Traceback (most recent call last):
      File "/home/a/Desktop/escape/mygame.py", line 4, in <module>
        from foo import *
      File "/home/a/Desktop/escape/game_data.py", line 2, in <module>
        imglist = [images.floor, images.pillar, images.soil]
    NameError: name 'images' is not defined

What is the correct way for one script to import another if both rely on pgzero functionality?

Thanks.

**Comment by lordmauve** [comment]
Actually, I think this is [fixed in master](https://github.com/lordmauve/pgzero/commit/d9b0da972904a5633e98a7e30b10453aaa2e3742#diff-7acccb08004c3e95b60efe8788216259) but not yet released.
