### ISSUE TITLE
Docs: Japanese translation

### ISSUE THREAD

**Issue by yasusii** [lordmauve/pgzero#187]
Hi, I'm working on the japanese translation of the pgzero documentation.

https://github.com/yasusii/pgzero-japanese

**Comment by lordmauve** [comment]
Wonderful! Thank you.

Let me know when you think it is ready to hook up to the official docs site.

**Comment by yasusii** [comment]
Hi, the japanese translation is done.

https://pgzero-japanese.readthedocs.io/ja/latest/

**Comment by lordmauve** [comment]
Hi @yasusii. Great work! ReadTheDocs changed their permissions. In order to connect this to the main docs page, I need to be a maintainer on the docs project. Please can you add `mauve` to the maintainers on this page: https://readthedocs.org/dashboard/pgzero-japanese/users/

**Comment by yasusii** [comment]
I just added you to the maintainer.

**Comment by lordmauve** [comment]
Wonderful! I have hooked it up: https://pygame-zero.readthedocs.io/ja/latest/

Thank you so much!
