### ISSUE TITLE
link on the tutorial web page is too new for the released version of pygame zero

### ISSUE THREAD

**Issue by Naohiro2g** [lordmauve/pgzero#192]
The tutorial document "Migrating from Scratch"
https://pygame-zero.readthedocs.io/en/stable/from-scratch.html
https://github.com/lordmauve/pgzero/commits/master/doc/from-scratch.rst

In this page there is a link to flappybird.py at github.com.  It is linked to the examples/flappybird/flappybird.py in master branch. The linked code is too new for the latest released pygamezero 1.2 and causes name not defined error for 'storage' because storage.py had introduced after 1.2 release.

The link on the tutorial page should be linked to the 1.2release branch.
https://github.com/lordmauve/pgzero/raw/1.2release/examples/flappybird/flappybird.py

**Comment by jolly-jump** [comment]
tried to fix it with #295 . Not 100% sure if the PR is against the correct branch though.

**Comment by lordmauve** [comment]
That fixes it, thanks!
