### ISSUE TITLE
New stackoverflow question tag "pgzero" created - please edit the tag description

### ISSUE THREAD

**Issue by aryoda** [lordmauve/pgzero#195]
I have created a new question tag called `pgzero` at www.stackoverflow.com to allow a better tagging of questions related to Pygame Zero.

Until now questions were tagged with `pygame` which is not really correct (even though `pgzero` uses `pygame`).

I have provided an initial tag description, please verify and edit (if required) the tag description as you want:

https://stackoverflow.com/edit-tag-wiki/139730

The current description is:

> `pgzero` (Pygame Zero) is a Python library providing a zero-boilerplate game development framework.
> It is based on the library `Pygame`.

**Comment by lordmauve** [comment]
Perfect! Thanks!
