### ISSUE TITLE
Other libraries like Pygame Zero: richlib

### ISSUE THREAD

**Issue by electronstudio** [lordmauve/pgzero#199]
I have made a library that attempts to be a 3d equivalent to Pygame Zero.  It's basically Raylib Zero but I called it Richlib to follow their naming convention!  It's far from complete but I've been using it for teaching purposes.  You have a web page where you list similiar libraries so perhaps you would like to add it?

https://github.com/electronstudio/richlib

**Comment by lordmauve** [comment]
Oh, very nice!

**Comment by lordmauve** [comment]
Are you still working on this library? I like the look of this but it needs thorough documentation before it is a good candidate to link to from Pygame Zero's docs.

I'm closing this issue for now but let me know if you want to take this forward and I'll re-open.

**Comment by electronstudio** [comment]
I paused development on it due to issues with Raylib (the underlying C library) being quite immature and frequently breaking.  I hope to pick it up again eventually assuming Raylib is smooth enough.
