### ISSUE TITLE
Introduction to Pygame code fail

### ISSUE THREAD

**Issue by madtom1999** [lordmauve/pgzero#206]
in the CLOCK section of the introduction
def on_mouse_down(pos):
    if alien.collidepoint(pos):
        sounds.eep.play()
        alien.image = 'alien_hurt'
        time.sleep(1)
        alien.image = 'alien'
the image doesnt change on screen. If I move to the next section with def set_alien_hurt(): the image does change. I'm guessing there is no re-draw in the event code until it returns?  Running this through Thonny with pgzrun.go()

**Comment by lordmauve** [comment]
This is given as an example of code that will not work.

> Unfortunately, this is not at all suitable for use in a game.
