### ISSUE TITLE
Use of sound files different to image files

### ISSUE THREAD

**Issue by DarrenTownsend** [lordmauve/pgzero#214]
Why is the method for playing wav files different from using image files?

EG. To show an image you first have to assign it:
alien = Actor('alien')
alien.draw()

whereas with sound files, the first step is skipped, just needing;
sounds.eep.play()

I would have expected to have to do;
eep = Sound('eep') or something similar.

This seems confusing.

**Comment by lordmauve** [comment]
The same API works for images. `screen.blit(images.alien)` is valid.

Also you can do `Actor(images.alien)` but this was removed from the documentation because the string approach is shorter and slightly easier to use - eg. `print(actor.image)` is meaningful.

**Comment by DarrenTownsend** [comment]
Ok, thank you. It just seems inconsistent. I would have expected the two things to work the same way. With the way that sounds works, it looks like you're acting on an object that you haven't instantiated. I know you don't actually use those phrases with Pygame Zero, but I've found that it's easier to teach if you can keep things consistent.

**Comment by lordmauve** [comment]
Sound and video are different. For a graphic, you _almost always_ want to attach state, such as where to draw it on the screen, rotation, or opacity. For a sound, you _almost never_ need state; in almost all games you don't want to do anything with a sound other than play it at the right moment.
