### ISSUE TITLE
import pgzrun - module not found

### ISSUE THREAD

**Issue by simonc8** [lordmauve/pgzero#215]
Trying to run a pgzero programme from Python following instructions on [https://pygame-zero.readthedocs.io/en/stable/ide-mode.html](https://pygame-zero.readthedocs.io/en/stable/ide-mode.html). First line in code is `import pgzrun` but this produces an error that the module is not found. Where is the module? Is it automatically downloaded when you do a pip install of pgzero?

**Comment by lordmauve** [comment]
`pgzrun` is included in the pgzero library.

Please can you include the output of `pip freeze`?

**Comment by simonc8** [comment]
Thanks for your reply.

[pip_freeze_out.txt](https://github.com/lordmauve/pgzero/files/4045362/pip_freeze_out.txt)

pgzero v 1.1 is listed. Does this need to be updated? There is no file pgzrun.py in the pgzero folder of my Python installation.

I was trying the flappybird Pygame Zero example game, and the function storage() was also not found, so I assume this is part of module pgzrun.

**Comment by lordmauve** [comment]
Yes, IDE mode aka `pgzrun` was added in 1.2: https://pygame-zero.readthedocs.io/en/latest/changelog.html

Storage is only available on the master branch. If you want to play the examples from master you need to install from master. I think that would be something like

```
pip install git://github.com/lordmauve/pgzero#egg=pgzero
```

**Comment by simonc8** [comment]
Thanks for the answer. 
I couldn't get the install from the master to work. The syntax may not be exactly right. At the bottom of a load of red text in the cmd window it said:
ValueError: Sorry, 'git://github.com/lordmauve/pgzero#egg=pgzero' is a malformed VCS url.

**Comment by lordmauve** [comment]
Oh, sorry, try

```
pip install git+https://github.com/lordmauve/pgzero#egg=pgzero
```

**Comment by simonc8** [comment]
Many thanks, Daniel. That works now.
Would it be worth adding a note to the flappybird project to say that it requires pgzero 1.3 from the master?

**Comment by lordmauve** [comment]
I think we just need to ship 1.3 ASAP.
