### ISSUE TITLE
screen.clear() implementation

### ISSUE THREAD

**Issue by sabahat70** [lordmauve/pgzero#218]
I am trying to implement a multi-screen game using pygame zero. I found an issue while trying to use screen.clear() to remove the previously drawn sprites on screen, and drawing new sprites on same screen to imitate a new screen , the previously drawn images become hidden however; the mouse_down event associated with them still triggers when I click my mouse on their ( previous sprites) locations. This suggests that those sprites are still on screen but hidden and not completely removed. Kindly look into this.

**Comment by lordmauve** [comment]
Please can you provide some example code that does not do what you expect?

**Comment by sabahat70** [comment]
I have Mac Catalina. The versions of Python, Pygame and Pygame Zero that I found to be compatible with Mac Catalina are 3.7, 2.0.0dev4 and 1.2 respectively where Python 3.7 was already preinstalled. 
In my code, when the scene_2 starts, the choose button is not there anymore on screen but pressing on that location still changes the avatar when it is not supposed to. Following is my code:
```
`#game settings
HEIGHT = 1000
WIDTH = 1000
gameScreen = 0
h = 100
w = 100

#global variables
avatars = []
currentavatar = 0

changeavatarbutton = Rect((20,20),(h,w))

def draw():
	
	if gameScreen == 0:
		scene_1()

	elif gameScreen == 1:
		scene_2()


def addavatars():
	for i in range(3):
		avatars.append(Actor('avatar'+str(i)))
	

def scene_1():
	screen.clear()
	screen.fill((255,255,255))
	avatars[currentavatar].pos = (HEIGHT/2,WIDTH/2)
	avatars[currentavatar].draw()
	screen.draw.filled_rect(changeavatarbutton,"orange")
	screen.draw.textbox("Choose",changeavatarbutton, color = ("black"))


def scene_2():
	screen.clear()
	screen.fill((255,255,255))
	avatars[currentavatar].draw()

def update():
	if keyboard.left:
		if avatars[currentavatar].x - 2 > 0:
			avatars[currentavatar].x = avatars[currentavatar].x - 2
	elif keyboard.right:
		if avatars[currentavatar].x + 2 < WIDTH:
			avatars[currentavatar].x = avatars[currentavatar].x + 2


def on_mouse_down(pos):
	global gameScreen,currentavatar
	
	if changeavatarbutton.collidepoint(pos):
		if currentavatar == 2:
			currentavatar = 0
		else:
			currentavatar = currentavatar + 1
	elif avatars[currentavatar].collidepoint(pos):
		gameScreen = gameScreen + 1
		

addavatars()`

```
I made it run as I wanted by adding another condition within the if checks under on_mouse_down function as under:
```
`def on_mouse_down(pos):
	global gameScreen,currentavatar
	
	if changeavatarbutton.collidepoint(pos) and gameScreen == 0:
		if currentavatar == 2:
			currentavatar = 0
		else:
			currentavatar = currentavatar + 1
	elif avatars[currentavatar].collidepoint(pos) and gameScreen == 1:
		gameScreen = gameScreen + 1` 
```

I had to do this because the screen.clear() did not behave as required. Plus, I feel if screen.clear() did remove the objects completely from screen then the if checks under on_mouse_down would give an error then as they would be checking for objects that do not exist anymore.

**Comment by lordmauve** [comment]
The problem is that you are not checking if `gameScreen == 0` in `on_mouse_down()`.

**Comment by sabahat70** [comment]
Hi Daniel!

Hope you are doing good! I actually mentioned this workaround in my sample
code. And I still don't understand why screen.clear() is just hiding the
button. I know deleting the button completely will create other issues.
However, can there be a functionality that can disable the body of the
button so that collidepoint does not work on it anymore? Kindly reply.

Best,
Sabahat
