### ISSUE TITLE
support for width argument in screen.draw.line 

### ISSUE THREAD

**Issue by qkzk** [lordmauve/pgzero#221]
Hello there, 

In the code source, I can see a `width` argument for `SurfacePainter.line` but I can't seem to use it
in code with `screen.draw.line(start, end, color, width=...)`. It always raises an error.

Is there a way around ?

I know it adds some complexity, since it's another parameter to consider, but it would be a nice addition.

Thanks in advance for your answer and the wonderfull work.

**Comment by qkzk** [comment]
Just to show you a quick way around (and to make you laugh since it's quick and dirty)...

```python
def neighbors(start, end, step):
    x_s, y_s = start
    x_e, y_e = end
    yield x_s + step, y_s, x_e + step, y_e
    yield x_s - step, y_s, x_e - step, y_e
    yield x_s, y_s + step, x_e, y_e + step
    yield x_s, y_s - step, x_e, y_e - step


def draw_line_width(start, end, color="white", width=1):
    screen.draw.line(start, end, color=color)
    for step in range(1, width):
        for x_s, y_s, x_e, y_e in neighbors(start, end, step):
            screen.draw.line((x_s, y_s), (x_e, y_e), color=color)
```

**Comment by lordmauve** [comment]
This seems to no longer be an issue under Pygame 2/SDL 2.
