### ISSUE TITLE
Pgzero won't work with PyGame2.0.0, which means newer Mac computers can't use it.

### ISSUE THREAD

**Issue by NotVeryGoodAtCodingButOk** [lordmauve/pgzero#223]
I am only asking for compatibility with PyGame 2.0.0 so that new mac models can use it. MacOs Catalina can't run Pygame 1.9.6, which is the version of pygame compatible with Pgzero. Fix this please!

**Comment by lordmauve** [comment]
What happens when you run it with Pygame 2?

**Comment by NotVeryGoodAtCodingButOk** [comment]
The installation of pgzero, since it requires pygame 1.9.6, will uninstall any other version of pygame you have on your machine, and install the necessary version of pygame.

P.D. I just wanted to tell you this so that you can work on bringing pgzero to newer Mac models.

**Comment by unspam** [comment]
> I am only asking for compatibility with PyGame 2.0.0 so that new mac models can use it. MacOs Catalina can't run Pygame 1.9.6, which is the version of pygame compatible with Pgzero. Fix this please!

Are you sure PyGame 1.9.6 doesn't actually run on Catalina? I believe it does run; however ver. 1.9.6 has frame rate issues on Retina displays, and consequently so does pgzero 1.2, which uses pygame 1.9.6. 
The frame rate issues are resolved in pygame 2 (which is still in beta though).

**However, I may have some good news:**
Today I installed pgzero using venv, which automatically installs pygame 1.9.6 as a dependency, and then upgraded the version of pygame to 2.0.0dev6. Then ran a fairly complex game I found on github, and it runs quite smoothly.
 
I was using the PyCharm IDE to do all this, so I'm embarassed to admit I don't know off-hand I would go about doing this via the terminal. (It shouldn't be difficult to do; I've just never gotten round to learning about the python package management ecosystem.)

**Comment by NotVeryGoodAtCodingButOk** [comment]
Hi @unspam and @lordmauve 
I tried to create a new virtualenv in PyCharm, and adding pgzero, but unfortunately my installation command threw the following error:
  error: command 'gcc' failed with exit status 1
Do you know why this may be happening? Can you help me? Thanks in advance to the both of you.

**Comment by NotVeryGoodAtCodingButOk** [comment]
but how do I run the command "pgzrun" in the terminal if only my venv environment has pgzero installed?

**Comment by unspam** [comment]
> but how do I run the command "pgzrun" in the terminal if only my venv environment has pgzero installed?

Have you taken a look at [this](https://pygame-zero.readthedocs.io/en/stable/ide-mode.html)?

**Comment by lgautier** [comment]
PR #207 and issue #225 seem related, and suggest a fix.

**Comment by dlebauer** [comment]
Now that #207 has been merged, can this be closed?

**Comment by lordmauve** [comment]
This has been addressed for the 1.2 branch. Future releases from master will use Pygame 2 also.
