### ISSUE TITLE
Cannot install pgzero

### ISSUE THREAD

**Issue by timension** [lordmauve/pgzero#231]
Have Python 3.9 and Pygame 2.0 installed. However, when I try to install Pygame Zero by typing `pip install pgzero` the installation exits with following error:

>     ERROR: Command errored out with exit status 1:
     command: 'c:\users\maxim\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Maxim\\AppData\\Local\\Temp\\pip-install-rgmxyd65\\pygame\\setup.py'"'"'; __file__='"'"'C:\\Users\\Maxim\\AppData\\Local\\Temp\\pip-install-rgmxyd65\\pygame\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Maxim\AppData\Local\Temp\pip-pip-egg-info-tg7ext7q'
         cwd: C:\Users\Maxim\AppData\Local\Temp\pip-install-rgmxyd65\pygame\
    Complete output (17 lines):

    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...

    Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Maxim\AppData\Local\Temp\pip-install-rgmxyd65\pygame\setup.py", line 194, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\Maxim\AppData\Local\Temp\pip-install-rgmxyd65\pygame\buildconfig\config.py", line 210, in main
        deps = CFG.main(**kwds)
      File "C:\Users\Maxim\AppData\Local\Temp\pip-install-rgmxyd65\pygame\buildconfig\config_win.py", line 576, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\Maxim\AppData\Local\Temp\pip-install-rgmxyd65\pygame\buildconfig\download_win_prebuilt.py", line 302, in ask
        reply = raw_input(
    EOFError: EOF when reading a line
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

What is wrong and how can I avoid the error?

**Comment by Redysz** [comment]
Workaround: `pip install pygame==2.0.0` then `pip install pgzero --no-deps`

**Comment by timension** [comment]
> Workaround: `pip install pygame==2.0.0` then `pip install pgzero --no-deps`

Thank you Redysz! It worked! 👍

**Comment by jhutar** [comment]
Hello. Or you can use devel version where it is fixed:

```
pip install git+https://github.com/lordmauve/pgzero.git
```

**Comment by frenzymadness** [comment]
Wouldn't it be better to release a new version of pgzero? The latest release is from 2018.

**Comment by lordmauve** [comment]
I've released a new version 1.2.1.
