### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by frenzymadness** [lordmauve/pgzero#234]
Hello.

There are 132 new commits in the master branch since the last release in February 2018. Isn't a time for the next release?

It'd also make pgzero installable from PyPI for Python > 3.8 and pygame > 2.0.

**Comment by fillwithjoy1** [comment]
@lordmauve

**Comment by lordmauve** [comment]
This is done for the 1.2 branch: pgzero should be installable again using Pygame wheels. For the work on master there is more effort needed to refine the feature set that should actually ship in 1.3. Some of the features and docs in Wasabi2D need to be backported and some half-finished features need to be removed.
