### ISSUE TITLE
works with pygame 2.0.1

### ISSUE THREAD

**Issue by MandiYang** [lordmauve/pgzero#239]
I use python3.8.5 and installed pygame 2.0.1 in a mystic way, pgzero 1.2 still works, OMG! plz make a new version which don't requires pygame < 2.0 and python_version < 3.8

**Comment by fillwithjoy1** [comment]
Not helpful, calling for issue to be closed @lordmauve

**Comment by lordmauve** [comment]
I've released 1.2.1 which supports (and requires) Pygame 2.0.*.

**Comment by MandiYang** [comment]
Thx :) I will follow you
