### ISSUE TITLE
pgzrun error

### ISSUE THREAD

**Issue by Bigspoonguy** [lordmauve/pgzero#241]
Just trying to write/run super basic games in pygame zero, but keep getting the following error:

C:\Users\dave>pgzrun Desktop\Python Games\intro.py
pygame 2.0.1 (SDL 2.0.14, Python 3.9.1)
Hello from the pygame community. https://www.pygame.org/contribute.html
Usage: pgzrun [options]

pgzrun: error: You must specify which module to run.

**Comment by lordmauve** [comment]
> pgzrun Desktop\Python Games\intro.py

You will need to quote this, e.g.

pgzrun "Desktop\Python Games\intro.py"

Or use `cd` to switch to that directory.

**Comment by fillwithjoy1** [comment]
Or you can add 
`import pgzrun` at the top of your code
and 
`pgzrun.go()` at the end of your code
