### ISSUE TITLE
Partial black screen if update callback not defined

### ISSUE THREAD

**Issue by dogwynn** [lordmauve/pgzero#248]
If the window dimensions extend beyond the end of the screen on first rendering (e.g. issue #247), and if there is not an `update` callback defined, then the the portion of the window outside of screen is not rendered. Furthermore, if the window is brought fully into view, the unrendered portion remains black.

pygame 2.0.1 (SDL 2.0.14, Python 3.9.1)
pgzero 1.2.1
Windows 10

![smaller](https://user-images.githubusercontent.com/1621000/110651062-b5c02e80-8180-11eb-9bd7-85d96f33c972.png)

**Comment by lordmauve** [comment]
I believe this is fixed in 126f7cf21e6c0cd493ddd14468f934f7506fa343 by handling the `VIDEOEXPOSE` event.
