### ISSUE TITLE
Get Error: name 'storage' is not defined

### ISSUE THREAD

**Issue by staatzstreich** [lordmauve/pgzero#256]
Hello,

i am new to python and pgzero... I found out that the wasabi2D engine has this feature with "storage"
I added 
`storage = {}`
bevor and I could start the game

https://github.com/lordmauve/pgzero/blob/5b32a183969af329aefe090198cc7f73efdf3c9f/examples/flappybird/flappybird.py#L20

**Comment by MandiYang** [comment]
Which version of pgzero are you using??????

**Comment by staatzstreich** [comment]
I am using 1.2.1 and the code is from master branch

**Comment by MandiYang** [comment]
Your problem is solved. Use pgzero version 1.3dev from master branch

**Comment by aaal** [comment]
Hi, I've just installed pgzero under Linux in a VirtualEnv with pip, following the installation instructions. I got the pgzero-1.2.1 version, and thus I have the bug with the storage component which is not available with the 1.2 version. How to overcome this difficulty the simplest way ? Thx !
