### ISSUE TITLE
Get Error：OSError: [WinError -2147221005] 无效的类字符串

### ISSUE THREAD

**Issue by MCTF-Alpha-27** [lordmauve/pgzero#257]

**Comment by streetartist** [comment]
I think You must give more information

**Comment by MCTF-Alpha-27** [comment]
I use the same code, but I cannot run it by using the newest version.
I don't know why, I can use it in pygame 1.9.6.
(I don't know what cause it, maybe it's about pygame?)

**Comment by MCTF-Alpha-27** [comment]
I use the same code, but I cannot run it by using the newest version.
I don't know why, I can use it in pygame version 1.9.6.
(I don't know what cause it, maybe it's about pygame?)

**Comment by MCTF-Alpha-27** [comment]
pgzero uses pygame as its front end, right?

**Comment by MCTF-Alpha-27** [comment]
![image](https://user-images.githubusercontent.com/85936935/125880186-ac23649e-9c17-4076-8c43-e0974dcf31b2.png)
![image](https://user-images.githubusercontent.com/85936935/125880256-d483ad8c-95a5-4bcc-9f7f-8fdf298cb1a5.png)

**Comment by MCTF-Alpha-27** [comment]
Well, I can use it now.
I guess it is a bug of pygame.

**Comment by lordmauve** [comment]
Those tracebacks put the error in [pyttsx3](https://pypi.org/project/pyttsx3/), not Pygame or Pygame Zero.
