### ISSUE TITLE
1.2.1 refuses to play ogg files from music folder, such as Code-The-Classics games

### ISSUE THREAD

**Issue by DoctorMikeReddy** [lordmauve/pgzero#260]
theme.ogg for the Code-The-Classics games works with pgzero 1.2 an Pygame 1.9.6 but will not work for 1.2.1 (which also requires pygame 2 or better)

**Comment by DoctorMikeReddy** [comment]
Samples from here https://github.com/Wireframe-Magazine/Code-the-Classics

**Comment by DoctorMikeReddy** [comment]
Using Python 3.8.10

**Comment by lordmauve** [comment]
I think this is unfortunately due to PyGame switching the supported music codecs that they include in wheel files. I've been able to play a .ogg file on Linux in the past week, is this on Windows?

**Comment by DoctorMikeReddy** [comment]
Yes, Windows 10 (latest version)

**Comment by DoctorMikeReddy** [comment]
I have installed 3.8.6 on my Alienware and theme.ogg in the music folder works again. Must be an interaction between python 3.8.10 and Pygame 2.0.1

**Comment by lordmauve** [comment]
Pygame devs have been putting effort into build automation and bug hunting so that the music codecs are correctly installed in wheels now. I think this can be closed.

**Comment by arganoid** [comment]
Here's the pygame issue about it. I have just seen this occur on someone else's machine, on a new installation of Pygame and pgzero. https://github.com/pygame/pygame/issues/2739
