### ISSUE TITLE
Getting updated image for actor?

### ISSUE THREAD

**Issue by eugene-bce** [lordmauve/pgzero#261]
I have a webcam image that updates every second (webcam.jpg)
`webacm = Actor('webcam')
`

How can I get PgZero to update the Actor image when the image updates?

**Comment by lordmauve** [comment]
You have to use plain PyGame features for this. Pygame has a [camera module](https://www.pygame.org/docs/ref/camera.html) or you can load the images using `pygame.image.load()`.
