### ISSUE TITLE
Position window on screen

### ISSUE THREAD

**Issue by was-dtech** [lordmauve/pgzero#263]
I can make the window fullscreen.  Is there a way to position the window on the screen?  As the window always starts with the top left corner in the middle of the screen.  Thank you for any help.

**Comment by ntoll** [comment]
This is a question we get a LOT via Mu related support channels. A sensible default of centre of the screen might be a helpful way to go with this..? In any case @was-dtech - you could probably configure the position of your game something like this: https://www.pygame.org/wiki/SettingWindowPosition (i.e. by dropping down to the underlying PyGame layer).

**Comment by lordmauve** [comment]
This was fixed in bf48fc964b5168d8e1e101a32adc2ac6cb685c69, pending release

**Comment by ntoll** [comment]
Perfect. Thanks @lordmauve - always one step ahead of the rest of us. ;-)

**Comment by was-dtech** [comment]
Thank you @lordmauve - my students will certainly appreciate the update 👍
