### ISSUE TITLE
pgzero stable ICON does not use images folder. 

### ISSUE THREAD

**Issue by JeremiahCheatham** [lordmauve/pgzero#268]
pgzero stable need complete relative path to image with full name.

    ICON = "images/icon.png"

pgzero current uses the images folder like the Actor class. 

    ICON = "icon"

This causes programs to crash when changing from one branch to the other.

**Comment by lordmauve** [comment]
This was fixed in 225bfe500d05218e71cb504ea2611b7611f76c02.
