### ISSUE TITLE
Unable to change image of sprite

### ISSUE THREAD

**Issue by jrmhaig** [lordmauve/pgzero#327]
When I try to use the [`image` setter on an Actor](https://github.com/lordmauve/pgzero/blob/5b68f3d49ed44cad131010f34a116a0d776b2089/pgzero/actor.py#L325-L330) I get the error `TypeError: 'str' object is not callable`. Here is a basic example that shows this;

```python
import pgzrun

ship = Actor('ship0')
ship.image('ship1')

pgzrun.go()
```

Am I using this incorrectly? I'm afraid I am not primarily a Python programmer so it is possible I have misunderstood.

**Comment by mrjonesmc** [comment]
You need to use ship.image = 'ship1'
ship.image is a property, not a function

**Comment by jrmhaig** [comment]
Thanks @mrjonesmc 

This is very helpful and demonstrates my lack of knowledge of Python decorators.

**Comment by jrmhaig** [comment]
This is not an issue, just my misunderstanding.
