### ISSUE TITLE
Provide persistent storage API

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#33]
Originally reported by: **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**

----------------------------------------

We should provide some sort of built-in shelve-style API to let users write savegame state to a sensible user data location.

If users attempt to do this themselves, for example by writing to a file in the current directory, it could cause problems when the game is distributed/installed.

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/33

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Probably should limit this to JSON in a dbm.gnu database or something, rather than pickles as with shelve. This will prevent people getting into problems with unpickling after code changes.

**Comment by lordmauve** [comment]
*Original comment by* **Ian Salmons (Bitbucket: [Avaren](https://bitbucket.org/Avaren), GitHub: [Avaren](https://github.com/Avaren))**:

----------------------------------------

First cut in pull request #31

**Comment by lordmauve** [comment]
Added in #99

**Comment by damienmckenna** [comment]
FYI the Pygame Zero [roadmap page](https://pygame-zero.readthedocs.io/en/stable/roadmap.html) still says this is a todo item rather than something that was already finished and committed, so it might be worth a quick moment to update the site.
