### ISSUE TITLE
Add screen.bounds

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#40]
Originally reported by: **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**

----------------------------------------

Add a method or property to get the Rect for the screen itself.

This would make it easier to test for collision with the edge of the screen.

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/40

**Comment by alisdt** [comment]
Taking a look at this one just now!

**Comment by alisdt** [comment]
Ignore the multiple commits, was just figuring out how git works (again)
