### ISSUE TITLE
Thumbs.db on windows

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#42]
Originally reported by: **Michael Grazebrook (Bitbucket: [mgrazebrook](https://bitbucket.org/mgrazebrook), GitHub: [mgrazebrook](https://github.com/mgrazebrook))**

----------------------------------------

Thumbs.db (note the capital) is created invisibly on Windows when you view a folder in the file manager. Because it has a capital, pgzero rejects it:

pgzero.loaders.InvalidCase 

It's hard for a beginner to debug as the file isn't visible in the file manager (or indeed using bash with 'ls' though 'ls -a' works).

Though to your credit the error message is excellent!

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/42

**Comment by charlesej** [comment]
I have tried to reproduce this issue, but have been unsuccessful.

The following files are in my `images` directory.

    alien.png
    Thumbs.db

Running this code works. The image is loaded without issue.

    actor = Actor('alien')


The following bits of code produce errors, but they are expected.

    actor = Actor('Thumbs.db')  # Attempt to directly load the `Thumbs.db` file.

Gives this error (same as mentioned above), but in this situation it is expected.
```
pgzero.loaders.InvalidCase: 'images\\Thumbs.db' is not lower case.
You must use lower case filenames. This is to avoid portability problems when run on another operating system (because filenames on some operating systems are case-sensitive and others are not).
```

    actor = Actor('thumbs.db')  # Attempt to directly load the `Thumbs.db` file, but use lowercase.

Gives this error as expected.

    pygame.error: Unsupported image format


System details:
- os: windows 10
- python: 3.5.0
- pygame: 1.9.4
- pgzero: 1.2
- numpy: 1.15.4

From the original issue description it sounds as if pgzero was attempting to pre-load files in the `images` directory. The current version of pgzero does not do this. If this pre-loading was causing the       problem, then this issue could be closed. If not, could you provide some more details on how to reproduce this issue?
Thanks.

**Comment by lordmauve** [comment]
Agreed.
