### ISSUE TITLE
Spell checking of WIDTH and HEIGHT

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#45]
Originally reported by: **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**

----------------------------------------

@TJG reports an issue with the spellchecking of WIDTH and HEIGHT when the capitalisation of these vairables is wrong.

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/45

**Comment by mbravn** [comment]
so sprinting at europython18 and trying to solve this
/Maria

**Comment by mbravn** [comment]
Can't seem to be able to reproduce the issue. Could you @lordmauve elaborate?

**Comment by lordmauve** [comment]
Closing as not reproducible
