### ISSUE TITLE
Can't run asteroids example

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#47]
Originally reported by: **Nigel Morse (Bitbucket: [musmuris](https://bitbucket.org/musmuris), GitHub: [musmuris](https://github.com/musmuris))**

----------------------------------------

Not sure what I'm doing wrong - but if I get the examples I get an error trying to run Asteroids:

```
#!

C:\dev\pygamezero\examples\asteroids>pgzrun main.py
Traceback (most recent call last):
  File "C:\Program Files\Python35\Scripts\pgzrun-script.py", line 9, in <module>
    load_entry_point('pgzero==1.1', 'console_scripts', 'pgzrun')()
  File "c:\program files\python35\lib\site-packages\pgzero\runner.py", line 88, in main
    exec(code, mod.__dict__)
  File "main.py", line 7, in <module>
    from space import create_star_scape
ImportError: No module named 'space'
```

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/47

**Comment by lordmauve** [comment]
*Original comment by* **Steve Clement (Bitbucket: [SteveClement](https://bitbucket.org/SteveClement), GitHub: [SteveClement](https://github.com/SteveClement))**:

----------------------------------------

I know this issue, no clue how to fix it so you can use pgzrun.

What does work is:

python3 -m pgzero main.py

Cheers.

**Comment by lordmauve** [comment]
*Original comment by* **Nigel Morse (Bitbucket: [musmuris](https://bitbucket.org/musmuris), GitHub: [musmuris](https://github.com/musmuris))**:

----------------------------------------

Oh yes - so it does!  How odd - but that works for me - cheers

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

- re #47 - monkeypatch fixed

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Merged in maho/pgzero (pull request #41)

Closes #47

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Merged in maho/pgzero (pull request #41)

Closes #47

**Comment by swirly** [comment]
The asteroid example still doesn't work for me
What I've done : 

- install pgzero on debian with apt-get install python3-pgzero
- download examples from github
- run them with pgzrun 

When running many exemples, everything works fine
not for asteroids

```shell
$ pgzrun main.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/bin/pgzrun", line 11, in <module>
    load_entry_point('pgzero==1.2', 'console_scripts', 'pgzrun')()
  File "/usr/lib/python3/dist-packages/pgzero/runner.py", line 92, in main
    exec(code, mod.__dict__)
  File "main.py", line 8, in <module>
    from actors import Player, Asteroid
  File "/home/cooperl/pgzero-master/examples/asteroids/actors.py", line 7, in <module>
    class Player(Actor):
NameError: name 'Actor' is not defined

```
The Actor class is available in other examples from basic directory, and they work fine

Modifier actors.py by adding
```python 
from pgzero.actor import *
```
But there are other errors
```shell
$ pgzrun main.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/bin/pgzrun", line 11, in <module>
    load_entry_point('pgzero==1.2', 'console_scripts', 'pgzrun')()
  File "/usr/lib/python3/dist-packages/pgzero/runner.py", line 93, in main
    run_mod(mod)
  File "/usr/lib/python3/dist-packages/pgzero/runner.py", line 113, in run_mod
    PGZeroGame(mod).run()
  File "/usr/lib/python3/dist-packages/pgzero/game.py", line 217, in run
    self.mainloop()
  File "/usr/lib/python3/dist-packages/pgzero/game.py", line 225, in mainloop
    self.reinit_screen()
  File "/usr/lib/python3/dist-packages/pgzero/game.py", line 65, in reinit_screen
    pygame.display.set_icon(pygame.image.load(icon))
pygame.error: Couldn't open player
```

As asteroids is alphabetically the first example, it should run flawlessly

**Comment by JeongJun-Lee** [comment]
How about increasing the pygame version to 2.x.x? And you need to comment 'ICON' at 9 lines in the main.py.

> The asteroid example still doesn't work for me What I've done :
> 
> * install pgzero on debian with apt-get install python3-pgzero
> * download examples from github
> * run them with pgzrun
> 
> When running many exemples, everything works fine not for asteroids
> 
> ```shell
> $ pgzrun main.py 
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Traceback (most recent call last):
>   File "/usr/bin/pgzrun", line 11, in <module>
>     load_entry_point('pgzero==1.2', 'console_scripts', 'pgzrun')()
>   File "/usr/lib/python3/dist-packages/pgzero/runner.py", line 92, in main
>     exec(code, mod.__dict__)
>   File "main.py", line 8, in <module>
>     from actors import Player, Asteroid
>   File "/home/cooperl/pgzero-master/examples/asteroids/actors.py", line 7, in <module>
>     class Player(Actor):
> NameError: name 'Actor' is not defined
> ```
> 
> The Actor class is available in other examples from basic directory, and they work fine
> 
> Modifier actors.py by adding
> 
> ```python
> from pgzero.actor import *
> ```
> 
> But there are other errors
> 
> ```shell
> $ pgzrun main.py 
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Traceback (most recent call last):
>   File "/usr/bin/pgzrun", line 11, in <module>
>     load_entry_point('pgzero==1.2', 'console_scripts', 'pgzrun')()
>   File "/usr/lib/python3/dist-packages/pgzero/runner.py", line 93, in main
>     run_mod(mod)
>   File "/usr/lib/python3/dist-packages/pgzero/runner.py", line 113, in run_mod
>     PGZeroGame(mod).run()
>   File "/usr/lib/python3/dist-packages/pgzero/game.py", line 217, in run
>     self.mainloop()
>   File "/usr/lib/python3/dist-packages/pgzero/game.py", line 225, in mainloop
>     self.reinit_screen()
>   File "/usr/lib/python3/dist-packages/pgzero/game.py", line 65, in reinit_screen
>     pygame.display.set_icon(pygame.image.load(icon))
> pygame.error: Couldn't open player
> ```
> 
> As asteroids is alphabetically the first example, it should run flawlessly
