### ISSUE TITLE
Running tests on OS X crashes Python

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#56]
Originally reported by: **Paweł Lewtak (Bitbucket: [pawel-lewtak](https://bitbucket.org/pawel-lewtak), GitHub: [pawel-lewtak](https://github.com/pawel-lewtak))**

----------------------------------------

This command:
`python3 setup.py test`

fails with following output:

test_blit_name (test.test_screen.ScreenTest)
screen.blit() accepts an image name instead of a Surface. ... FAIL
test_blit_surf (test.test_screen.ScreenTest)
We can blit a surface to the screen. ... FAIL
test_load_11kgsm (test.test_sound_formats.SoundFormatsTest) ... Python(10810,0x7fffd763f3c0) malloc: *** error for object 0x1036fb1a0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    10810 abort      python3 setup.py test

Detailed log is in the attachment.

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/56

**Comment by lucas-james** [comment]
@lordmauve I couldn't reproduce this - tests seem to run fine for me 👍

**Comment by tmontes** [comment]
@lordmauve,

Exploring the possibilities of contributing, I ran into this. I agree with @lucas-james, on my system, running macOS 10.12.6, tests complete perfectly fine both under Python 3.6.8 and 3.7.4.

Maybe this issue can be closed? :)

**Comment by lordmauve** [comment]
Yes, I think would be a Pygame bug anyway.
