### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#60]
Originally reported by: **Anonymous**

----------------------------------------

I have successfully installed pygame zero on a Mac, but I'm having a problem installing it on my windows laptop.  I was getting the error "could not create" "permission denied" when I ran *pip install pgzero* in the command line.  I tried changing it to *pip install pgzero --user* which did load successfully, but I'm not sure if it really did install because when I use the runner pgzrun, I get another error stating "pgzrun is not recognized as an internal or external command".  Help!

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/60

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Hi, could you run

echo %PATH%

and post the result? By guess is that the Python "bin" directory is not on your path, so pgzrun on its own does not work.

**Comment by lordmauve** [comment]
*Original comment by* **tallteacher1 (Bitbucket: [tallteacher1](https://bitbucket.org/tallteacher1), GitHub: Unknown)**:

----------------------------------------

Thanks for the response, Daniel!
I don't think bin is in my directory.  A print is below of my command line after I entered
echo %PATH%
Any help is greatly appreciated!  I'm hoping to starting a unit next week with my high school students on pgzero, If I can get it installed.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Student>pip install pgzero
Collecting pgzero
  Using cached pgzero-1.1.tar.gz
Requirement already satisfied: pygame>=1.9 in c:\users\student\appdata\roaming\p
ython\python36\site-packages (from pgzero)
Installing collected packages: pgzero
  Running setup.py install for pgzero ... error
    Complete output from command "c:\program files (x86)\python36-32\python.exe"
 -u -c "import setuptools, tokenize;__file__='C:\\Users\\Student\\AppData\\Local
\\Temp\\pip-build-lf6517ca\\pgzero\\setup.py';f=getattr(tokenize, 'open', open)(
__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __fil
e__, 'exec'))" install --record C:\Users\Student\AppData\Local\Temp\pip-h50u_y3z
-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\pgzero
    copying pgzero\actor.py -> build\lib\pgzero
    copying pgzero\animation.py -> build\lib\pgzero
    copying pgzero\builtins.py -> build\lib\pgzero
    copying pgzero\clock.py -> build\lib\pgzero
    copying pgzero\constants.py -> build\lib\pgzero
    copying pgzero\game.py -> build\lib\pgzero
    copying pgzero\keyboard.py -> build\lib\pgzero
    copying pgzero\loaders.py -> build\lib\pgzero
    copying pgzero\music.py -> build\lib\pgzero
    copying pgzero\ptext.py -> build\lib\pgzero
    copying pgzero\rect.py -> build\lib\pgzero
    copying pgzero\runner.py -> build\lib\pgzero
    copying pgzero\screen.py -> build\lib\pgzero
    copying pgzero\soundfmt.py -> build\lib\pgzero
    copying pgzero\spellcheck.py -> build\lib\pgzero
    copying pgzero\__init__.py -> build\lib\pgzero
    copying pgzero\__main__.py -> build\lib\pgzero
    running install_lib
    creating c:\program files (x86)\python36-32\Lib\site-packages\pgzero
    error: could not create 'c:\program files (x86)\python36-32\Lib\site-package
s\pgzero': Access is denied

    ----------------------------------------
Command ""c:\program files (x86)\python36-32\python.exe" -u -c "import setuptool
s, tokenize;__file__='C:\\Users\\Student\\AppData\\Local\\Temp\\pip-build-lf6517
ca\\pgzero\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().
replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install -
-record C:\Users\Student\AppData\Local\Temp\pip-h50u_y3z-record\install-record.t
xt --single-version-externally-managed --compile" failed with error code 1 in C:
\Users\Student\AppData\Local\Temp\pip-build-lf6517ca\pgzero\

C:\Users\Student>echo %PATH%
C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;
C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:
\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\Window
sPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Compon
ents\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Pro
gram Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program File
s\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common
Files\Lenovo;C:\ProgramData\Lenovo\ReadyApps

C:\Users\Student>echo %PATH%

**Comment by lordmauve** [comment]
*Original comment by* **Tim Golden (Bitbucket: [TJG](https://bitbucket.org/TJG), GitHub: [TJG](https://github.com/TJG))**:

----------------------------------------

Oddly I'm seeing everything *except* the PATH output there. Just to clarify what seems to be happening:

* You have a system install of Python 3.6 which sits in the admin-protected "c:\program files (x86)" area.
* When you run pip install <whatever> you're doing a system-level pip install (because you haven't specified --user) but you're operating as a regular user, not an admin.

* From that point you have two options: (a) use pip install --user (which what you did); or (b) elevate the command prompt [Run as Administrator] which will run the "pip install" command as an admin and should succeed. The former is preferable to avoid cluttering the system Python with lots of packages, but you clearly know your own setup best.

* On top of that, having (presumably) successfully installed pgzero into the user path for pip installations -- probably %APPDATA%\python\python36 -- the pgzrun command will be in the scripts folder under that directory (in my case C:\Users\goldent\AppData\Roaming\Python\Python36\Scripts). If that scripts folder isn't on the system PATH then pgzrun won't be recognised when you attempt to run it at the command line.

Which is why you're being asked for the PATH contents.

As a rule this will usually work even when pgzrun isn't on the path:

py -mpgzero 

(That tells the Python launcher to invoke the __main__ module for the pgzero package -- which is essentially what pgzrun does)

although that assumes you have the Python launcher ("py") installed. You probably do for that version of Python but it is an option on the installer.

**Comment by lordmauve** [comment]
*Original comment by* **tallteacher1 (Bitbucket: [tallteacher1](https://bitbucket.org/tallteacher1), GitHub: Unknown)**:

----------------------------------------

Tim,
Thank you.  That was very helpful.  I was able to install using:
pip install pgzero --user
I can run my program through the command line with: 

py -mpgzero [file name]

I am going to post my command line printout below, because I'm still confused why I cannot just use pgzrun since my pgzrun command is in the scripts folder just like you listed for yours (C:\Users\Legacy Staff\AppData\Roaming\Python\Python36\Scripts\pgzrun)

My command line print out with error message:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Legacy Staff>pip install pgzero --user
Requirement already satisfied: pgzero in c:\users\legacy staff\appdata\roaming\p
ython\python36\site-packages
Requirement already satisfied: pygame>=1.9 in c:\users\legacy staff\appdata\roam
ing\python\python36\site-packages (from pgzero)

C:\Users\Legacy Staff>cd PgZero

C:\Users\Legacy Staff\PgZero>pgzrun intro.py
'pgzrun' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by lordmauve** [comment]
*Original comment by* **Tim Golden (Bitbucket: [TJG](https://bitbucket.org/TJG), GitHub: [TJG](https://github.com/TJG))**:

----------------------------------------

If you take the PATH output you pasted above and drop it into a text editor, and then search for "Scripts" -- the only one listed there is the system-wide "C:\Program Files (x86)\Python36-32\Scripts". Your own user-specific "c:\users\legacy staff\appdata\roaming\python\python36\scripts" isn't shown, because the Python installer only adds it if you do a user-local install. In short -- assuming you know how to do this -- if you add "c:\users\legacy staff\appdata\roaming\python\python36\scripts" to the PATH in your user environment variables, that should allow pgzrun to be used on the command-line as is.

**Comment by lordmauve** [comment]
*Original comment by* **tallteacher1 (Bitbucket: [tallteacher1](https://bitbucket.org/tallteacher1), GitHub: Unknown)**:

----------------------------------------

Okay.  Great!  I will try that.

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

@tallteacher1 Are you still having problems with this? I'm marking this as resolved; we can re-open if it's not.

**Comment by vblume** [comment]
Hi, 
I have added the path:

C:\Users\rmblu>echo %PATH%
C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Users\rmblu\AppData\Local\Microsoft\WindowsApps;

However; I still have this error and couldnt figure out why? 

C:\Users\rmblu>'pgzrun' is not recognized as an internal or external command,
''pgzrun'' is not recognized as an internal or external command,
operable program or batch file.

Can you please help
