### ISSUE TITLE
Failing test in the latest release

### ISSUE THREAD

**Issue by frenzymadness** [lordmauve/pgzero#66]
Hello.

I am updating pgzero to the latest version in Fedora and I've found two issues in the new `test_tone.py` test.

* First one is on line 6 where import should be changed from `from tone import note_to_hertz, validate_note, InvalidNote` to `from pgzero.tone import note_to_hertz, validate_note, InvalidNote`.
* Second one is on line 35 where regexp doesn't match actual InvalidNote exception text. There is a comma in `is not a valid note,` but dot in `is not a valid note.` in the original function.

BTW nice to see that you migrated from Bitbucket to Github. Great decision.

Thank you and have a nice day.
Lumír

**Comment by lordmauve** [comment]
That is (slightly) surprising, as I ran all tests just before release. But not implausible, still. How are you running tests?

One of the reasons I moved to Github was so that I could try to set up Travis to run tests so this kind of oversight doesn't happen.

**Comment by frenzymadness** [comment]
With freshly downloaded pgzero sources from PyPI:

```
# cd /builddir/build/BUILD/pgzero-1.2/
<mock-chroot> sh-4.4# python3 -m unittest discover test/
.................................E...
======================================================================
ERROR: test_tone (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_tone
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/builddir/build/BUILD/pgzero-1.2/test/test_tone.py", line 6, in <module>
    from tone import note_to_hertz, validate_note, InvalidNote
ModuleNotFoundError: No module named 'tone'


----------------------------------------------------------------------
Ran 37 tests in 0.017s

FAILED (errors=1)
```
Then I fixed import as mentioned in the issue description.

```
# python3 -m unittest discover test/
....................................F...
======================================================================
FAIL: test_validate_note (test_tone.ToneTest)
----------------------------------------------------------------------
pgzero.tone.InvalidNote: A9 is not a valid note. notes are A-F, are either normal, flat (b) or sharp (#) and of octave 0-8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/builddir/build/BUILD/pgzero-1.2/test/test_tone.py", line 36, in test_validate_note
    validate_note(note)
AssertionError: "A9\ is\ not\ a\ valid\ note\,\ notes\ are\ A\-F\,\ are\ either\ normal\,\ flat\ \(b\)\ or\ sharp\ \(\#\)\ and\ of\ octave\ 0\-8" does not match "A9 is not a valid note. notes are A-F, are either normal, flat (b) or sharp (#) and of octave 0-8"

----------------------------------------------------------------------
Ran 40 tests in 0.029s

FAILED (failures=1)
```
There is a difference between actual and expected exception text. Just changed comma to dot.

```
# python3 -m unittest discover test/
........................................
----------------------------------------------------------------------
Ran 40 tests in 0.019s

OK
```

If you need any selp with Travis set up, let me know.

**Comment by lordmauve** [comment]
Ok, yes, can reproduce. I'm also seeing awful crash bugs with the sound file loading tests all of a sudden.

**Comment by frenzymadness** [comment]
I forget to mention that I am not running test_screen.py, test_actor.py and test_sound_formats.py because I am building the Fedora package in a headless environment so I cannot access output devices.

That's the reason why I found a bug only in one file/test.
