### ISSUE TITLE
black dots in circle border when drawing with custom pensize

### ISSUE THREAD

**Issue by yonghuming** [lordmauve/pgzero#68]
i have update the code in screen.py so i can draw images with custom pensize, but the output seems strange.
```    
def circle(self, pos, radius, color, pensize = 1):
        """Draw a circle."""
        pos = round_pos(pos)
        pygame.draw.circle(self._surf, make_color(color), pos, radius, pensize)
```
then i draw circle with pensize 10
```
def draw():
    screen.clear()
    screen.draw.circle((400, 300), 300, 'red', 10)
```
so, you can see there are black dots in circle border
![image](https://user-images.githubusercontent.com/435079/36704216-5d289162-1b9a-11e8-82eb-63969fb6cf8e.png)

**Comment by lordmauve** [comment]
This is an pygame/pygame#388, fixed in pygame/pygame#389.
