### ISSUE TITLE
help translating to Chinese language

### ISSUE THREAD

**Issue by yonghuming** [lordmauve/pgzero#72]
help translating to Chinese language

**Comment by yonghuming** [comment]
link to my repository https://github.com/yonghuming/pgzero-cn

**Comment by yonghuming** [comment]
http://pgzero-cn.readthedocs.io/zh_CN/latest/ readthedocs links

**Comment by lordmauve** [comment]
This is now linked to the main Pygame Zero documentation, and visible at http://pygame-zero.readthedocs.io/zh_CN/latest/
