### ISSUE TITLE
errors in docs 

### ISSUE THREAD

**Issue by yonghuming** [lordmauve/pgzero#73]
![image](https://user-images.githubusercontent.com/435079/37400106-beb2cfda-27be-11e8-9e86-ef6916e19493.png)

**Comment by yonghuming** [comment]
maybe i should do a pr

**Comment by lordmauve** [comment]
Yes, please!

**Comment by yonghuming** [comment]
@lordmauve also, this should be constan property of Animate

**Comment by lordmauve** [comment]
Fixed by #109.
