### ISSUE TITLE
class Actor should have a images list property so easy to make animation

### ISSUE THREAD

**Issue by yonghuming** [lordmauve/pgzero#74]
![image](https://user-images.githubusercontent.com/435079/37401381-d6dd3772-27c2-11e8-97d0-8e799c8108a8.png)
we should allow users to config a list of images for actor 
and implement iter method 
next costume => next_image
switch costume to... => switch_image_to
ando so on 
```
class Actor():
    ...
    images = []
    
    def next_image():
        pass
    def switch_image( image_name ):
       pass
 

```

**Comment by lordmauve** [comment]
You can assign to `image` on an Actor. I just looked though, and this is not documented under Actor (it is in the tutorial). 😖

I don't think actors need a list of images. It's easy enough to write this functionality using the existing API.

**Comment by yonghuming** [comment]
```
    images = []

    def add_image(self, image_name):
        self.images.append(image_name)
    
    def next_image(self):
        # need clock to do async
        # update 
        idx = self.images.index(self.image)
        # todo: 
        if idx == len(self.images) - 1:
            idx = -1
        print(idx)
        self.image = self.images[idx + 1]


    def switch_image(self, image_name = ''):
        self.image = image_name
```

**Comment by yonghuming** [comment]
just make pygame zero more scratch-like and made it easier maigrate from scratch to python

**Comment by yonghuming** [comment]
maybe you are right

**Comment by yonghuming** [comment]
@lordmauve do you know cocos python, also a 2d game framework but based pyglet, and seems easier to use than pygame, i suggestion you have a try, and it has more feature, seems cocos python is protype of cocos2d js and cocos2dx

**Comment by lordmauve** [comment]
I know it well. I gave a keynote at Pycon Poland last year that talked about [the history of Cocos2D](http://mauveweb.co.uk/posts/2017/08/fun-and-games.html).

However it doesn't run on Raspberry Pi, I believe, and the audio stuff has been broken on Linux recently and is hard to get working on Windows. I've seen some graphics driver issues with Pyglet too. These problems are inconvenient for experts but may be insurmountable for beginners.

**Comment by yonghuming** [comment]
@lordmauve oh, thank you for tell me this

**Comment by lordmauve** [comment]
Closing as partially duplicates #43
